### ISSUE TITLE
Change Swagger generator

### ISSUE THREAD

**Issue by vrann** [magento-engcom/bulk-api#11]
# Add Asynchronous Swagger Schema 

[Magento\WebapiAsync](https://github.com/magento/bulk-api-ee/pull/1/files) creates asynchronous versions of the WebAPI. 

The asynchronous endpoint accepts the same payload as the regular rest endpoint. It provides different responses, eg
 
**Magento\Webapi**
```
POST /rest/V1/products/

HTTP/1.1 200 OK
{
  "sku" : "abc"
}
```

**Magento\WebapiAsync**
```
POST /async/V1/products/

HTTP/1.1 202 Accepted
{
  "bulk_uuid": "abcd",
  "error": "Some error"
}
```

Currently, the `Magento\Webapi\Model\Rest\Swagger\Generator` class only outputs a Swagger definition describing the existing rest endpoints. 

The `Magento\WebapiAsync` module needs to add Swagger output for the asynchronous versions of each of the endpoints. 

This was initially implemented under https://github.com/magento/bulk-api-ce/pull/1/commits/c09f916752aa2a07a80cb936c06da278c8adb146 , but has since been reverted and extracted to this issue.

---

## Acceptance Criteria 

- [ ] Visiting https://example.org/swagger/ in browser outputs same Swagger schema as it did previously (backwards-compatibility) 
- [ ] Visiting https://example.org/swagger/type/rest/ in browser outputs the schema relating to `Magento\Webapi`
- [ ]  Visiting https://example.org/swagger/type/async/ in browser outputs the schema relating to `Magento\WebapiAsync` (asynchronous) 
- [ ] Asynchronous Swagger schema describes the possible response bodies supplied by `Magento\WebapiAsync`, and applicable HTTP response codes
----

## Tasks: 

1. Extract common generator functionality into new dependencies for use between Magento Open Source & Commerce 
2. Refactor Open Source generator using new dependencies for `rest` endpoint 
3. Implement asynchronous generator in Magento Commerce (describing functionality added in https://github.com/magento/bulk-api-ee/pull/1)
4. Add asynchronous generator in Magento Commerce for `async` endpoint 
5. Update Unit & Integration tests 
6. Add MFTF acceptance tests for Swagger UI to check that:
    - Magento Open Source Swagger UI describes non-asynchronous rest endpoint output 
    - Magento Commerce Swagger UI describes both rest endpoint and async endpoints

**Comment by careys7** [comment]
@maximbaibakov I have added some acceptance criteria and a further description of the work required on this

**Comment by careys7** [comment]
We need to return a hardcoded response object during schema generation if the schema generation is running for async output. 

Magento_Webapi currently does this using the [`ClassReflector`](https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/Webapi/Model/Config/ClassReflector.php#L30). `ClassReflector::reflectClassMethods()` is invoked by [`Webapi\Model\ServiceMetadata`](https://github.com/magento/bulk-api-ce/blob/2.3-develop/app/code/Magento/Webapi/Model/ServiceMetadata.php#L125). 

---

# Problem:

1. Some services need to be explicitly defined as non-async (such as the status reporting API). Others might require this in the future.

---

# Solutions

## 1. Add a `SynchronousInterface` to indicate that a service is synchronous-only

```php
interface BulkStatusManagement implements SynchronousInterface {} 
```

Pros:
- Easy to interpret within `ClassReflector`

Cons:
- Potential to increase coupling of MagentoWebapiAsync with other modules due to code reference (not ideal). Currently the only usage would be within the scope of 
- Can only apply to entire service, rather than a particular operation 

## 2. Implement an annotation:

```php
interface BulkStatusManagement
{
    /**
      * @synchronousInvocationOnly
      */
    public function getStatus($id);
}
```

Pros:
- Easy to interpret within `ClassReflector`

Cons:
- Adds WebApi context-awareness into what are otherwise generic services 

## 3. XML - Apply the parameter using the `<data>` node available from webapi.xsd configuration

```xml
<routes xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_Webapi:etc/webapi.xsd">

    <route url="/V1/bulk/status/:bulkUuid" method="GET">
        <service class="Magento\AsynchronousOperations\Api\BulkRepositoryInterface" method="getBulkDetails"/>
        <resources>
            <resource ref="Magento_Logging::system_magento_logging_bulk_operations" />
        </resources>
        <data>
            <parameter name="synchronousInvocationOnly" />
        </data>
    </route>

</routes>
```

Pros:
- Moves asynchronous logic into `ServiceMetadata` class instead of `ClassReflector` (which by its name suggests that strictly processes class reflections, and doesn't implement additional logic)

Cons:
- Adds async references into XML for other modules (coupling)


## 4. XML - Add a new webapi_async.xml configuration format

Allow modules to specify individual methods for services which do not support async

 ```xml
<services xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:noNamespaceSchemaLocation="urn:magento:module:Magento_WebapiAsync:etc/webapi_async.xsd">

        <service class="Magento\AsynchronousOperations\Api\BulkRepositoryInterface" method="getBulkDetails">
           <synchronousInvocationOnly />
        </service>

</services>
```

Pros:
- Best modularity 
- We can add other asynchronous configuration in the future if needed 

Cons:
- Currently there is only one resource that needs this 
- Not mapped directly to `webapi.xsd`'s `<route>` node. Doing this would require code duplication. Not doing this means that we might not be able to configure other route-related parameters for asynchronous communication in the future.  
---

My current preference is option 4. 

@nuzil / @vrann / @misha-kotov / @anvasiliev / @paliarush - can you give feedback on the above?

**Comment by careys7** [comment]
Reviewed the above today in sync up meeting:

- Ok to proceed with the implementation based on number 4. DI would have been a preference initially because of the lack of current use cases but as the `webapi_async.xml` configuration has already been implemented this can stay for now. 

- Ok to reference Context / HTTP dependencies in ServiceMetadata plugin for WebapiAsync. It is assumed that other usages of the ServiceMetadata are likely to require HTTP context, or in cases like CLI, they will implement a separate plugin with separate dependencies. 

- We still need to define how the ServiceMetadata plugin is reading information related to the context to determine if the Swagger generation is executing for the rest or async schema. It is likely that [this if statement](https://github.com/magento/bulk-api-ce/pull/4/files#diff-da6e1bd59641565ee3d1c03b01d4750eR43) needs to be extracted into some sort of interface which we can inject into the ServiceMetadata plugin [here](https://github.com/magento/bulk-api-ee/pull/3/files#diff-b718306b54290083db3de47aa7fcd92eR29), so that we know if the plugin's logic should be executed. @vrann can you confirm the best approach here?

**Comment by anvasiliev** [comment]
Related to _"We need to return a hardcoded response object during schema generation if the schema generation is running for async output."_ I added AsyncResponseInterface which we can use like definition for each async request Response Class output in swagger for async webapi.
https://github.com/magento/bulk-api-ee/pull/1/commits/c51646d4ba4d602036999a6fecb1a683d657a246#diff-a9bac09a1555928ca4b845787fa7241a
